#!/usr/bin/env bash
TAKOMA_CONFIG="$HOME/.takoma.json"
TAKOMA_VERSION="0.1"
TAKOMA_CACHE="$HOME/.takoma_current_version"

package=""  
target="" 

hash jq 2>/dev/null || { echo >&2 "Takoma needs 'jq' to be installed.  Aborting."; exit 1; }

while getopts ":h" opt; do
  case ${opt} in
    h )
      echo "Usage:"
      echo "    -h   Display this help message."
      echo "    list List takoma environments."
      echo "    switch <environment> Switch environment."
      echo "    current Show current environment."
      exit 0
      ;;
   \? )
     echo "Invalid Option: -$OPTARG" 1>&2
     exit 1
     ;;
  esac
done
shift $((OPTIND -1))

switch_aws_credentials()
{
    aws_access_key_id=$(cat $TAKOMA_CONFIG|jq '.'$environment'.aws_access_key_id'|tr -d '"')
    aws_secret_access_key=$(cat $TAKOMA_CONFIG|jq '.'$environment'.aws_secret_access_key'|tr -d '"')
    region=$(cat $TAKOMA_CONFIG|jq '.'$environment'.region'|tr -d '"')
    
    echo "# This file was automatically generated by Takoma at $(date)
[default]
aws_access_key_id = $aws_access_key_id
aws_secret_access_key = $aws_secret_access_key
region = $region
"> $HOME/.aws_credentials
    echo "~/.aws_credentials"
}

subcommand=$1; shift  
case "$subcommand" in
    version)
        echo "Takoma version: " $TAKOMA_VERSION
        ;;
    list)
        package=$1; shift 
        cat $TAKOMA_CONFIG | jq 'keys'|jq -r '.[]'
        ;;
    current)
        cat $TAKOMA_CACHE
        ;;
    switch)
        environment=$1
        echo "Switching to environment:" $environment
        switch_aws_credentials
        #switch_s3cmd_credentials
        #switch_boto_credentials
        #switch_fog_credentials
        #switch_route53_credentials
        echo $environment > $TAKOMA_CACHE
        ;;
esac
